title: "Excellence Emmanuel Jnr"
email: excellencee78@gmail.com
description: >-
  Cybersecurity | Blue Team | Threat Intel | Portfolio + Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://excel-tech1.github.io" # your domain

twitter_username: Cyber_Xcellence
github_username: Excel-Tech1

# Build settings
theme: null
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-remote-theme 
  - jekyll-include-cache
  - jekyll-feed



collections:
  pages:
    output: true

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      css: "custom"

# Optional: Exclude from build (optional cleanup)
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/

